# k8s/monitoring/values.yaml
grafana:
  adminPassword: "Admin@123"
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    ingressClassName: azure-application-gateway
    hosts:
      - grafana.app.4.193.226.111.nip.io
    path: /
    pathType: Prefix
  persistence:
    enabled: false

prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        release: kps
    serviceMonitorNamespaceSelector: {}

alertmanager:
  service:
    type: ClusterIP

prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi