name: App (Build & Deploy)

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - "backend/**"
      - "k8s/**"
  workflow_dispatch:

env:
  ACR_NAME: grp3acr
  AKS_RG: rg-grp3-aks
  AKS_NAME: aks-grp3
  K8S_NAMESPACE: grp3
  FRONTEND_IMAGE: grp3acr.azurecr.io/frontend
  BACKEND_IMAGE: grp3acr.azurecr.io/backend
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: ACR Login
        run: az acr login -n $ACR_NAME

      # Build & Push images
      - name: Build Frontend
        run: |
          docker build -t $FRONTEND_IMAGE:${IMAGE_TAG} ./frontend
          docker push $FRONTEND_IMAGE:${IMAGE_TAG}
      - name: Build Backend
        run: |
          docker build -t $BACKEND_IMAGE:${IMAGE_TAG} ./backend
          docker push $BACKEND_IMAGE:${IMAGE_TAG}

      # Set Kube context
      - name: Get AKS Credentials (user)
        run: |
          az aks get-credentials -g $AKS_RG -n $AKS_NAME --overwrite-existing --admin false

      # Patch images (اختياري إن ما تستخدمين Helm)
      - name: Set images
        run: |
          kubectl -n $K8S_NAMESPACE set image deployment/frontend frontend=$FRONTEND_IMAGE:${IMAGE_TAG} || true
          kubectl -n $K8S_NAMESPACE set image deployment/backend  backend=$BACKEND_IMAGE:${IMAGE_TAG}   || true

      # Apply manifests (تحافظ على المتغيرات مثل VITE_API_BASE_URL في الـ Deployment)
      - name: Apply K8s Manifests
        run: |
          kubectl -n $K8S_NAMESPACE apply -f k8s/backend/
          kubectl -n $K8S_NAMESPACE apply -f k8s/frontend/

      - name: Wait for Rollout
        run: |
          kubectl -n $K8S_NAMESPACE rollout status deployment/frontend --timeout=120s
          kubectl -n $K8S_NAMESPACE rollout status deployment/backend  --timeout=120s