name: Infra (Terraform)

on:
  pull_request:
    paths: [ "infra/**/*.tf", "infra/**/*.tfvars" ]
  workflow_dispatch:

jobs:
  plan:
    name: Terraform Plan (no destroy gate)
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Azure login using Service Principal + secret
      - name: Azure Login (Service Principal)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.ARM_CLIENT_SECRET }}

      # Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Initialize Terraform
      - name: Terraform Init
        working-directory: infra
        run: terraform init -upgrade

      # Run Terraform plan
      - name: Terraform Plan
        id: plan
        working-directory: infra
        run: |
          set -e
          terraform plan -out=plan.tfplan -no-color -detailed-exitcode || echo "exit_code=$?" >> $GITHUB_OUTPUT
          terraform show -no-color plan.tfplan > plan.txt

      # Fail if plan contains Destroy
      - name: Fail if plan contains Destroy
        working-directory: infra
        run: |
          destroys=$(grep -Eo 'Destroy: [0-9]+' plan.txt | awk '{print $2}')
          if [ -n "$destroys" ] && [ "$destroys" -gt 0 ]; then
            echo "❌ Plan contains destroys ($destroys). Failing as requested."
            exit 1
          fi
          echo "✅ No destroys detected."

      # Upload plan result as artifact
      - name: Upload plan result
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan
          path: infra/plan.txt
